### ISSUE TITLE
WebApp sends redundant SubscribeButton(PLAY_PAUSE) request 

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_javascript_suite#320] opened 2020-09-22 10:45 UTC
**Bug Report**
WebApp sends redundant SubscribeButton(PLAY_PAUSE) request 

**Preconditions:**

1. HMI and SDL are started
2. Web app is registered and activated successfully HMI displays the WEB_VIEW template

**Reproduction Steps**

Press "Show menu" button on HMI
1. Web app sends ShowAppMenu: {}

**Expected Behavior**

    SDL → HMI: UI.ShowAppMenu:{"appID" : param}
    HMI → SDL: UI.ShowAppMenu:{ code":0 }
    SDL → Web app: ShowAppMenu:{"resultCode": "SUCCESS ", "success":true}
    Web app does not send SubscribeButton ({"buttonName":"PLAY_PAUSE"}) request to SDL

**Observed Behavior**

    SDL → HMI: UI.ShowAppMenu:{"appID" : param}
    HMI → SDL: UI.ShowAppMenu:{ code":0 }
    SDL → Web app: ShowAppMenu:{"resultCode": "SUCCESS ", "success":true}
    Web app sends SubscribeButton ({"buttonName":"PLAY_PAUSE"}) request to SDL

**OS & Version Information**

OS/Version: Ubuntu 18.04
HMI: 6d32f1b

Logs
[SDL_logs.zip](https://github.com/smartdevicelink/sdl_javascript_suite/files/5260820/SDL_logs.zip)

**Comment by VjKlepikov** [comment] 2020-09-22 10:49
Please notice this is regression issue.

**Comment by AKalinich-Luxoft** [comment] 2020-09-22 16:10
@theresalech please notice PR with fix is ready for Livio review

**Comment by theresalech** [comment] 2020-09-23 14:08
@AKalinich-Luxoft can you please pull the latest `develop` and let us know if this issue is still reproducible?

**Comment by AKalinich-Luxoft** [comment] 2020-09-24 15:05
@theresalech latest develop does not have that issue with PLAY_PAUSE button.
This is a regression caused by changes done in #307 
And it was fixed by Livio in #315 

However, latest develop is still have an issues with another button subscriptions and the logic of subscription itself. That's why fix is still required here.

**Comment by theresalech** [comment] 2020-09-24 15:40
@AKalinich-Luxoft, thanks for your response! We will close this issue as what you've cited for PLAY_PAUSE is resolved on `develop`. Can you please submit a new issue with details of other button subscriptions/logic of subscription? If PR #319 resolves the new issue, please reference that there as well. Thanks!

**Closed by theresalech** 2020-09-24 15:40 UTC
Labels: 1.2 Release
