### ISSUE TITLE
Unexpected GetSystemCapability error in the browser console

### ISSUE THREAD

**Issue by vladmu** [smartdevicelink/sdl_javascript_suite#222] opened 2020-05-13 08:30 UTC
##### Bug Report
After opening the `examples/webengine/hello-sdl` the `GetSystemCapability for type DISPLAYS returned with response code DATA_NOT_AVAILABLE` error alongside with the `null` displays twice in the console.

![image](https://user-images.githubusercontent.com/2202092/81785481-0cc88900-9507-11ea-943a-faf21d9310dc.png)

##### Reproduction Steps
1. Start Core and HMI
2. Run `examples/webengine/hello-sdl/index.js` 
3. Open Developer Tools
3. The error is shown in the console

##### Expected Behavior
No errors in the console

##### Observed Behavior
The `GetSystemCapability for type DISPLAYS returned with response code DATA_NOT_AVAILABLE` error alongside with the `null` displays twice in the console. There is no possibility to catch and manage the error to avoid the console output.

##### Browser & Version Information
* Browser and Version: Google Chrome 81.0.4044.138 (Official Build) (64-bit)
* SDL JavaScript Suite Module: `examples/webengine/hello-sdl`
* SDL JavaScript Version: 1.0.0
* Testing Against: The run of the WebEngine example

##### Test Case, Sample Code, and / or Example App
This line of code adds `OnSystemCapabilityListener` for `SystemCapabilityType.DISPLAYS`:

https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/_SubManagerBase.js#L176

When the `SystemCapabilityManager` tries to `updateCapability` for the given type in this line:
https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/SystemCapabilityManager.js#L450
the `GetSystemCapability` RPC returns `DATA_NOT_AVAILABLE` result code instead of expected `SUCCESS` or `WARNINGS`
https://github.com/smartdevicelink/sdl_javascript_suite/blob/965b3bd7a6cfa6912b94d3de92a6763dfca0fb91/lib/js/src/manager/SystemCapabilityManager.js#L415-L423

**Comment by vladmu** [comment] 2020-08-03 08:35
Reproducible in version 1.1.0

**Comment by renonick87** [comment] 2021-02-25 21:43
@vladmu Can you confirm whether this bug is still reproducible?

**Comment by renonick87** [comment] 2021-03-04 18:19
I'm unable to reproduce this bug in the current version so I'll be closing this issue. If you find that the issue still exists then we can reopen the issue.

**Closed by renonick87** 2021-03-04 18:19 UTC
